# This is a basic workflow to help you get started with Actions

name: BuildReleases

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:      
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: setup node.js
        uses: actions/setup-node@v4.0.1

      - name: install npm packages
        run: npm i adm-zip
        
      - name: run node.js script
        run: node github-actions-nodejs/pack.js

      - name: commit to Builds branch
        env:
          USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
        run: |
          git config --global user.email "${USER_EMAIL}"
          git config --global user.name "tairasoul"
          git stash

          git clean -fd

          git fetch origin builds || git checkout -b builds

          git stash apply
          
          cd Builds

          git pull origin builds --rebase

          git add .

          git commit -m "Generate new zip files"

          git push origin builds
